// Create a function, that accepts an arbitrary number of arrays and returns 
// a single array generated by alternately appending elements from the passed 
// in arguments. If one of them is shorter than the others, the result should 
// be padded with empty elements.

function interleave(...args) {
   const maxIndex = args.reduce((acc, next, i) => {
      if (next.length > acc['max']) {
         acc['max'] = next.length;
         acc['index'] = i;
      }
      return acc;
   }, {
      max: 0,
      index: 0
   }).index;
   return args[maxIndex].reduce((acc, n, i) => {
      args.forEach(el => el[i] === 0 ? acc.push(el[i]) : acc.push(el[i] || null));
      return acc;
   }, []);
}
console.log(interleave([1, 2, 3], [0, 0, 2, 10, 100], [1, 2]));